name: "ci"

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: run sdk tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: installing dependencies
        run: npm ci

      - name: run tests
        run: npm run test:ci
        env:
          WHITELISTED_WALLET_PRIVATE_KEY: ${{ secrets.WHITELISTED_WALLET_PRIVATE_KEY }}
          SELLER_ENTITY_ID: ${{ secrets.SELLER_ENTITY_ID }}
          SELLER_AGENT_WALLET_ADDRESS: ${{ secrets.SELLER_AGENT_WALLET_ADDRESS }}

      - name: uploads results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-results-${{ matrix.node-version }}
          path: junit.xml
